remote_theme: just-the-docs/just-the-docs
nav_sort: case_insensitive

nav_external_links:
  - title: matlab2github on GitHub
    url: https://github.com/magnesium2400/matlab2github/tree/main
    hide_icon: false 
    opens_in_new_tab: true
